/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/receipts/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Receipt */
        post: operations["parse_receipt_api_receipts_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Summary */
        get: operations["get_session_summary_api_sessions__session_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session By Id */
        get: operations["get_session_by_id_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Claims */
        post: operations["create_claims_api_sessions__session_id__claims_post"];
        /** Delete Claim */
        delete: operations["delete_claim_api_sessions__session_id__claims_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Paid */
        post: operations["mark_paid_api_sessions__session_id__payments_post"];
        /** Unmark Paid */
        delete: operations["unmark_paid_api_sessions__session_id__payments_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_parse_receipt_api_receipts_parse_post */
        Body_parse_receipt_api_receipts_parse_post: {
            /** Image */
            image: string;
        };
        /** ClaimItemRequest */
        ClaimItemRequest: {
            /**
             * Itemid
             * Format: uuid
             */
            itemId: string;
            /** Quantity */
            quantity: number;
        };
        /** ClaimResponse */
        ClaimResponse: {
            /**
             * Itemid
             * Format: uuid
             */
            itemId: string;
            /** Itemname */
            itemName: string;
            /** Quantity */
            quantity: number;
        };
        /** CreateClaimsRequest */
        CreateClaimsRequest: {
            /** Participantname */
            participantName: string;
            /** Claims */
            claims: components["schemas"]["ClaimItemRequest"][];
        };
        /** CreateClaimsResponse */
        CreateClaimsResponse: {
            /** Participantname */
            participantName: string;
            /** Claims */
            claims: components["schemas"]["ClaimResponse"][];
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Hostpaynowid */
            hostPaynowId: string;
            /** Items */
            items: components["schemas"]["SessionItemRequest"][];
            /**
             * Taxrate
             * @default 0.09
             */
            taxRate: number;
            /**
             * Servicechargerate
             * @default 0.1
             */
            serviceChargeRate: number;
            /**
             * Discount
             * @default 0
             */
            discount: number;
            /**
             * Participantcount
             * @default 1
             */
            participantCount: number;
            /** Name */
            name?: string | null;
        };
        /** CreateSessionResponse */
        CreateSessionResponse: {
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            /** Name */
            name: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** DeleteClaimRequest */
        DeleteClaimRequest: {
            /** Participantname */
            participantName: string;
            /**
             * Itemid
             * Format: uuid
             */
            itemId: string;
        };
        /** GetSessionResponse */
        GetSessionResponse: {
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            /** Name */
            name: string;
            /** Hostpaynowid */
            hostPaynowId: string;
            /** Items */
            items: components["schemas"]["SessionItemResponse"][];
            /** Taxrate */
            taxRate: number;
            /** Servicechargerate */
            serviceChargeRate: number;
            /** Discount */
            discount: number;
            /** Participantcount */
            participantCount: number;
            /**
             * Claims
             * @default []
             */
            claims: components["schemas"]["SessionClaimResponse"][];
            /**
             * Payments
             * @default []
             */
            payments: components["schemas"]["SessionPaymentResponse"][];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ListSessionsResponse */
        ListSessionsResponse: {
            /** Sessions */
            sessions: components["schemas"]["SessionListItem"][];
        };
        /** ParsedItem */
        ParsedItem: {
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unitprice */
            unitPrice: number;
            /** Confidence */
            confidence?: number | null;
        };
        /** ParsedReceipt */
        ParsedReceipt: {
            /** Items */
            items: components["schemas"]["ParsedItem"][];
            /** Tax */
            tax: number;
            /** Servicecharge */
            serviceCharge: number;
            /** Rawtext */
            rawText: string;
        };
        /** ParticipantSummary */
        ParticipantSummary: {
            /** Name */
            name: string;
            /** Itemssubtotal */
            itemsSubtotal: number;
            /** Proportionaltax */
            proportionalTax: number;
            /** Proportionalservicecharge */
            proportionalServiceCharge: number;
            /** Proportionaldiscount */
            proportionalDiscount: number;
            /** Totalowed */
            totalOwed: number;
        };
        /** PaymentRequest */
        PaymentRequest: {
            /** Participantname */
            participantName: string;
        };
        /** PaymentResponse */
        PaymentResponse: {
            /** Participantname */
            participantName: string;
            /** Paid */
            paid: boolean;
            /** Paidat */
            paidAt?: string | null;
        };
        /** SessionClaimResponse */
        SessionClaimResponse: {
            /** Participantname */
            participantName: string;
            /**
             * Itemid
             * Format: uuid
             */
            itemId: string;
            /** Itemname */
            itemName: string;
            /** Quantity */
            quantity: number;
        };
        /** SessionItemRequest */
        SessionItemRequest: {
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unitprice */
            unitPrice: number;
        };
        /** SessionItemResponse */
        SessionItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unitprice */
            unitPrice: number;
        };
        /** SessionListItem */
        SessionListItem: {
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            /** Name */
            name: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** SessionPaymentResponse */
        SessionPaymentResponse: {
            /** Participantname */
            participantName: string;
            /**
             * Paidat
             * Format: date-time
             */
            paidAt: string;
        };
        /** SessionSummaryResponse */
        SessionSummaryResponse: {
            /** Rawsubtotal */
            rawSubtotal: number;
            /** Tax */
            tax: number;
            /** Servicecharge */
            serviceCharge: number;
            /** Discount */
            discount: number;
            /** Grandtotal */
            grandTotal: number;
            /** Taxrate */
            taxRate: number;
            /** Servicechargerate */
            serviceChargeRate: number;
            /** Participants */
            participants: components["schemas"]["ParticipantSummary"][];
            unclaimed: components["schemas"]["UnclaimedSummary"];
        };
        /** UnclaimedItem */
        UnclaimedItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unitprice */
            unitPrice: number;
        };
        /** UnclaimedSummary */
        UnclaimedSummary: {
            /** Items */
            items: components["schemas"]["UnclaimedItem"][];
            /** Subtotal */
            subtotal: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    parse_receipt_api_receipts_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_receipt_api_receipts_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query: {
                hostPaynowId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSessionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_summary_api_sessions__session_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_by_id_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_claims_api_sessions__session_id__claims_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClaimsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateClaimsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_claim_api_sessions__session_id__claims_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteClaimRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_paid_api_sessions__session_id__payments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unmark_paid_api_sessions__session_id__payments_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
